name: Vibliotek
favicon: null
layout_spectrum: 0.09216164471581578
typography_spectrum: 0.9984385007992387
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3068336120340973
  lightness: 0.8684148525353521
  saturation: 0.5086450083181262
  rhythmicContrast: 0.5564379678107798
purpose: []
